spring:
  application:
    name: turbine
  # change this to the production values including the user/password
  rabbitmq:
    host: localhost
    port: 5672
    #username: guest
    #password: guest


PREFIX:
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

info:
  app:
    name: Turbine Server
    description: The Turbine Server
    version: ${project.version}
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}