info:
  component: Turbine

PREFIX:
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

server:
  port: 8989

security:
  basic:
    enabled: false
  user:
    name: libertasuser
    password: SecretPassword

management:
  port: 8990
  context-path: /manage
  security:
    enabled: false


logging:
  level:
    root: INFO
    com.netflix.discovery: 'OFF'
    # org.springframework.integration: DEBUG

eureka:
  client:
    # enable these two settings if you want discovery to work
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      # we use the secure form having user/password in the main
      defaultZone: http://localhost:8761/eureka/
  # this describes the actual instance that is registered and parameters around it
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /manage/info
    homePageUrlPath: /manage
    healthCheckUrlPath: /manage/health
    preferIpAddress: true
